AWSTemplateFormatVersion: '2010-09-09'
Resources:
  WebServerSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: WebServerSG
      GroupDescription: permit ssh and http
      SecurityGroupIngress:
        - IpProtocol: tcp
          ToPort: 22
          FromPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: vpc-d18befb6
